/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/terminology/code-systems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List loaded code systems
         * @description Every loaded code system release with its concept count.
         */
        get: operations["list_terminology_code_systems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/terminology/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search codes by code or text
         * @description Code-shaped queries ('K35', 'k3530', 'K35.3') always return codes with that prefix in tabular order. Otherwise `mode` picks the method:
         *
         *     - **text** — PostgreSQL full-text search (word stems, any order) + trigram similarity (typos) over the description and inclusion terms.
         *     - **semantic** — nearest codes by embedding similarity (pgvector); finds lay wording like 'heart attack'. Needs the embedding server.
         *     - **hybrid** — both rankings merged with reciprocal rank fusion; each hit reports its `text_rank` and `semantic_rank`.
         */
        get: operations["search_terminology_concepts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/terminology/concepts/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one code with its hierarchy and notes
         * @description Accepts dotted or undotted ICD-10-CM codes ('K35.30' or 'K3530'). Returns the parent, direct children, inclusion terms and tabular notes (excludes1/2, code first, use additional code, 7th character), plus `inherited_notes` from ancestor categories, which apply to this code too.
         */
        get: operations["get_terminology_concept"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coding/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Decision engines and coding thresholds
         * @description Engines selectable with ?engine=, the default, and the thresholds that set flags.
         */
        get: operations["get_coding_settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coding/encounters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List encounters (review queue) */
        get: operations["list_coding_encounters"];
        put?: never;
        /**
         * Submit a SOAP note and its findings for coding
         * @description Stores the encounter, then for every coded item (coding.coded_item_types — conditions in the prototype): hybrid search -> top candidates -> decision engine probabilities -> assigned code + flags. Other item types are stored as not_coded. Runs synchronously and returns the coded encounter.
         */
        post: operations["create_coding_encounter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coding/encounters/{encounter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a coded encounter
         * @description Each coded item's ai_classification (assigned code, probability, flags, ranked alternatives) beside its human review, plus the encounter audit_trail.
         */
        get: operations["get_coding_encounter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coding/encounters/{encounter_id}/items/{item_id}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All search candidates for one item, with probabilities
         * @description The full top-N the decision engine scored (not just the alternatives shown on the encounter), in search order: search rank/score, text and semantic ranks, matched index term, and the active decision's probability and rank.
         */
        get: operations["get_coding_item_candidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coding/encounters/{encounter_id}/items/{item_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve, override or remove one item's code
         * @description approve = accept the assigned code · override = replace it with `code` (any billable ICD-10-CM code) · remove = don't bill this item. The AI's assignment is kept alongside; every action is audited.
         */
        post: operations["review_coding_item"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coding/encounters/{encounter_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve the encounter (isHumanReviewed = true)
         * @description Allowed once every coded item is approved, overridden or removed.
         */
        post: operations["approve_coding_encounter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coding/encounters/{encounter_id}/rescore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-run a decision engine over the stored candidates
         * @description No new search. Replaces each item's active decision and clears item reviews. Not allowed once the encounter is approved.
         */
        post: operations["rescore_coding_encounter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 if the process is running. Does not check the database.
         */
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Returns 200 only when the database is reachable.
         */
        get: operations["readiness_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIClassification */
        AIClassification: {
            /** Engine */
            engine: string;
            /** Model */
            model?: string | null;
            /** Assigned Code */
            assigned_code: string | null;
            /** Assigned Description */
            assigned_description: string | null;
            /** Probability */
            probability: number | null;
            /** None Of The Above Probability */
            none_of_the_above_probability: number;
            /** Flags */
            flags: string[];
            /** Top Alternatives */
            top_alternatives: components["schemas"]["Alternative"][];
            /** Candidates Scored */
            candidates_scored: number;
            /** Latency Ms */
            latency_ms?: number | null;
        };
        /** Alternative */
        Alternative: {
            /** Code */
            code: string;
            /** Description */
            description: string;
            /** Probability */
            probability: number;
            /** Search Rank */
            search_rank: number;
            /** Matched On */
            matched_on?: string | null;
        };
        /** AuditTrail */
        AuditTrail: {
            /** Ishumanreviewed */
            isHumanReviewed: boolean;
            /** Reviewed By */
            reviewed_by?: string | null;
            /** Reviewed At */
            reviewed_at?: string | null;
            /** Final Billing Codes */
            final_billing_codes: string[];
        };
        /**
         * CandidateOut
         * @description One stored search candidate for an item, with the active decision's
         *     probability for it.
         */
        CandidateOut: {
            /** Code */
            code: string;
            /** Description */
            description: string;
            /** Search Rank */
            search_rank: number;
            /** Search Score */
            search_score?: number | null;
            /** Text Rank */
            text_rank?: number | null;
            /** Semantic Rank */
            semantic_rank?: number | null;
            /** Matched On */
            matched_on?: string | null;
            /**
             * Variants
             * @default []
             */
            variants: string[];
            /** Probability */
            probability?: number | null;
            /** Probability Rank */
            probability_rank?: number | null;
            /** Is Assigned */
            is_assigned: boolean;
            /** Is Final */
            is_final: boolean;
        };
        /** ClinicalInput */
        ClinicalInput: {
            /** Soap Note */
            soap_note: string;
            /** Department */
            department?: string | null;
        };
        /**
         * ClinicalItemIn
         * @description One finding from the note — already extracted upstream (Stage 0 is
         *     out of scope here). `text` is what gets searched; `details` keeps the
         *     rest of the source record (status, value, dose, dates …) untouched.
         */
        ClinicalItemIn: {
            /**
             * Text
             * @example acute appendicitis with localized peritonitis
             */
            text: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
        };
        /** CodeSystemListResponse */
        CodeSystemListResponse: {
            /** Total */
            total: number;
            /** Data */
            data: components["schemas"]["CodeSystemResponse"][];
        };
        /** CodeSystemResponse */
        CodeSystemResponse: {
            /** Id */
            id: number;
            /** Canonical Url */
            canonical_url: string;
            /** Version */
            version: string;
            /** Name */
            name: string;
            /** Title */
            title?: string | null;
            /** Publisher */
            publisher?: string | null;
            /** Active */
            active: boolean;
            /** Concept Count */
            concept_count: number;
            /** Embedded Count */
            embedded_count: number;
            /** Index Term Count */
            index_term_count: number;
            /** Index Terms Embedded */
            index_terms_embedded: number;
            /** Embedding Model */
            embedding_model: string;
        };
        /** CodedItemOut */
        CodedItemOut: {
            /** Item Id */
            item_id: number;
            /** Item Type */
            item_type: string;
            /** Sequence */
            sequence: number;
            /** Text */
            text: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status: string;
            /** Error */
            error?: string | null;
            ai_classification?: components["schemas"]["AIClassification"] | null;
            review: components["schemas"]["ItemReviewState"];
        };
        /** CodingSettings */
        CodingSettings: {
            /** Default Engine */
            default_engine: string;
            /** Engines */
            engines: components["schemas"]["EngineInfo"][];
            /** Coded Item Types */
            coded_item_types: string[];
            /** Candidates Per Item */
            candidates_per_item: number;
            /** Alternatives Shown */
            alternatives_shown: number;
            /** Low Confidence Threshold */
            low_confidence_threshold: number;
            /** Nota Flag Threshold */
            nota_flag_threshold: number;
        };
        /** ConceptDetailResponse */
        ConceptDetailResponse: {
            /** Code */
            code: string;
            /** Display */
            display: string;
            /** Short Display */
            short_display?: string | null;
            /** Is Billable */
            is_billable: boolean;
            /** System */
            system: string;
            /** Version */
            version: string;
            parent?: components["schemas"]["ConceptSummary"] | null;
            /** Children */
            children: components["schemas"]["ConceptSummary"][];
            /** Synonyms */
            synonyms: string[];
            /** Notes */
            notes: {
                [key: string]: string[];
            };
            /** Inherited Notes */
            inherited_notes: components["schemas"]["InheritedNotes"][];
        };
        /** ConceptSummary */
        ConceptSummary: {
            /** Code */
            code: string;
            /** Display */
            display: string;
            /** Short Display */
            short_display?: string | null;
            /** Is Billable */
            is_billable: boolean;
        };
        /** EncounterApprove */
        EncounterApprove: {
            /** Reviewer */
            reviewer: string;
        };
        /** EncounterCreate */
        EncounterCreate: {
            /**
             * Encounter Id
             * @example enc_2026_98312A
             */
            encounter_id: string;
            /**
             * Patient Id
             * @example pat_4412
             */
            patient_id: string;
            /**
             * Department
             * @example Emergency Medicine
             */
            department?: string | null;
            /** Soap Note */
            soap_note: string;
            /** Conditions */
            conditions?: components["schemas"]["ClinicalItemIn"][];
            /** Observations */
            observations?: components["schemas"]["ClinicalItemIn"][];
            /** Service Requests */
            service_requests?: components["schemas"]["ClinicalItemIn"][];
            /** Medication Requests */
            medication_requests?: components["schemas"]["ClinicalItemIn"][];
        };
        /** EncounterListResponse */
        EncounterListResponse: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Data */
            data: components["schemas"]["EncounterSummary"][];
        };
        /** EncounterOut */
        EncounterOut: {
            /** Encounter Id */
            encounter_id: string;
            /** Patient Id */
            patient_id: string;
            /** Status */
            status: string;
            /** Review Queue */
            review_queue?: string | null;
            clinical_input: components["schemas"]["ClinicalInput"];
            /** Coded Concepts */
            coded_concepts: components["schemas"]["CodedItemOut"][];
            audit_trail: components["schemas"]["AuditTrail"];
            /** Created At */
            created_at?: string | null;
        };
        /** EncounterSummary */
        EncounterSummary: {
            /** Encounter Id */
            encounter_id: string;
            /** Patient Id */
            patient_id: string;
            /** Department */
            department?: string | null;
            /** Status */
            status: string;
            /** Review Queue */
            review_queue?: string | null;
            /** Is Human Reviewed */
            is_human_reviewed: boolean;
            /** Items */
            items: number;
            /** Flagged Items */
            flagged_items: number;
            /** Created At */
            created_at?: string | null;
        };
        /** EngineInfo */
        EngineInfo: {
            /** Name */
            name: string;
            /** Engine */
            engine: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "decision_model" | "stand_in";
            /** Route */
            route?: string | null;
            /** Model */
            model?: string | null;
            /** Is Default */
            is_default: boolean;
            /** Warning */
            warning?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InheritedNotes
         * @description Notes declared on an ancestor category, which apply to this code too.
         */
        InheritedNotes: {
            /** Code */
            code: string;
            /** Display */
            display: string;
            /** Notes */
            notes: {
                [key: string]: string[];
            };
        };
        /** ItemCandidatesResponse */
        ItemCandidatesResponse: {
            /** Encounter Id */
            encounter_id: string;
            /** Item Id */
            item_id: number;
            /** Text */
            text: string;
            /** Search Query */
            search_query?: string | null;
            /** Engine */
            engine?: string | null;
            /** Model */
            model?: string | null;
            /** None Of The Above Probability */
            none_of_the_above_probability?: number | null;
            /** Final Code Not In Candidates */
            final_code_not_in_candidates?: string | null;
            /** Total */
            total: number;
            /** Candidates */
            candidates: components["schemas"]["CandidateOut"][];
        };
        /** ItemReview */
        ItemReview: {
            /**
             * Action
             * @enum {string}
             */
            action: "approve" | "override" | "remove";
            /** Reviewer */
            reviewer: string;
            /** Code */
            code?: string | null;
        };
        /** ItemReviewState */
        ItemReviewState: {
            /** Action */
            action?: string | null;
            /** Final Code */
            final_code?: string | null;
            /** Final Description */
            final_description?: string | null;
            /** Reviewed By */
            reviewed_by?: string | null;
            /** Reviewed At */
            reviewed_at?: string | null;
        };
        /** SearchHit */
        SearchHit: {
            /** Code */
            code: string;
            /** Display */
            display: string;
            /** Short Display */
            short_display?: string | null;
            /** Is Billable */
            is_billable: boolean;
            /** Score */
            score?: number | null;
            /** Text Rank */
            text_rank?: number | null;
            /** Semantic Rank */
            semantic_rank?: number | null;
            /** Matched On */
            matched_on?: string | null;
            /**
             * Variants
             * @default []
             */
            variants: string[];
        };
        /** SearchResponse */
        SearchResponse: {
            /** System */
            system: string;
            /** Version */
            version: string;
            /** Query */
            query: string;
            /**
             * Match Type
             * @enum {string}
             */
            match_type: "code" | "text" | "semantic" | "hybrid";
            /** Total */
            total: number | null;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Data */
            data: components["schemas"]["SearchHit"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_terminology_code_systems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeSystemListResponse"];
                };
            };
        };
    };
    search_terminology_concepts: {
        parameters: {
            query: {
                /** @description e.g. 'acute appendicitis with localized peritonitis', 'heart attack' or 'K35.3' */
                q: string;
                /** @description text | semantic | hybrid (default from configs/config.yaml) */
                mode?: "text" | "semantic" | "hybrid";
                /** @description Code system canonical URL */
                system?: string;
                /** @description Release, e.g. '2027'. Default: latest loaded */
                version?: string | null;
                /** @description Exclude non-billable category headers */
                billable_only?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Embedding server unreachable (semantic/hybrid) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_terminology_concept: {
        parameters: {
            query?: {
                /** @description Code system canonical URL */
                system?: string;
                /** @description Release, e.g. '2027'. Default: latest loaded */
                version?: string | null;
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConceptDetailResponse"];
                };
            };
            /** @description Code or code system not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_coding_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodingSettings"];
                };
            };
        };
    };
    list_coding_encounters: {
        parameters: {
            query?: {
                /** @description standard | close_review */
                queue?: string | null;
                /** @description processing | ready_for_review | reviewed | failed */
                status?: string | null;
                /** @description Filter on isHumanReviewed */
                reviewed?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_coding_encounter: {
        parameters: {
            query?: {
                /** @description Decision engine (default: coding.default_engine in configs/config.yaml) */
                engine?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EncounterCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterOut"];
                };
            };
            /** @description Encounter already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_coding_encounter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterOut"];
                };
            };
            /** @description Encounter not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_coding_item_candidates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemCandidatesResponse"];
                };
            };
            /** @description Encounter or item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_coding_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemReview"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterOut"];
                };
            };
            /** @description Encounter or item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not allowed in the current state */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    approve_coding_encounter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EncounterApprove"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterOut"];
                };
            };
            /** @description Encounter not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Items still unreviewed, or already approved */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rescore_coding_encounter: {
        parameters: {
            query?: {
                /** @description Decision engine (default: coding.default_engine in configs/config.yaml) */
                engine?: string | null;
            };
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    readiness_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
