"""coding pipeline tables

Revision ID: 20e12ee5e03e
Revises: c4d7a9e2b5f1
Create Date: 2026-09-26 15:08:04.463909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20e12ee5e03e'
down_revision: Union[str, None] = 'c4d7a9e2b5f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_encounter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('encounter_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('soap_note', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('review_queue', sa.String(), nullable=True),
    sa.Column('is_human_reviewed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_encounter_encounter_id'), 'coding_encounter', ['encounter_id'], unique=True)
    op.create_index(op.f('ix_coding_encounter_patient_id'), 'coding_encounter', ['patient_id'], unique=False)
    op.create_index(op.f('ix_coding_encounter_review_queue'), 'coding_encounter', ['review_queue'], unique=False)
    op.create_index(op.f('ix_coding_encounter_status'), 'coding_encounter', ['status'], unique=False)
    op.create_table('coding_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('encounter_pk', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_query', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('assigned_concept_id', sa.Integer(), nullable=True),
    sa.Column('assigned_code', sa.String(), nullable=True),
    sa.Column('assigned_display', sa.String(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('nota_probability', sa.Float(), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('final_concept_id', sa.Integer(), nullable=True),
    sa.Column('final_code', sa.String(), nullable=True),
    sa.Column('final_display', sa.String(), nullable=True),
    sa.Column('review_action', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_concept_id'], ['terminology_concept.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['encounter_pk'], ['coding_encounter.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['final_concept_id'], ['terminology_concept.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('encounter_pk', 'sequence', name='uq_coding_item_encounter_sequence')
    )
    op.create_index(op.f('ix_coding_item_encounter_pk'), 'coding_item', ['encounter_pk'], unique=False)
    op.create_index(op.f('ix_coding_item_status'), 'coding_item', ['status'], unique=False)
    op.create_table('coding_audit_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('encounter_pk', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['encounter_pk'], ['coding_encounter.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['coding_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_audit_event_encounter_pk'), 'coding_audit_event', ['encounter_pk'], unique=False)
    op.create_index(op.f('ix_coding_audit_event_item_id'), 'coding_audit_event', ['item_id'], unique=False)
    op.create_table('coding_candidate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('display', sa.String(), nullable=False),
    sa.Column('search_rank', sa.Integer(), nullable=False),
    sa.Column('search_score', sa.Float(), nullable=True),
    sa.Column('text_rank', sa.Integer(), nullable=True),
    sa.Column('semantic_rank', sa.Integer(), nullable=True),
    sa.Column('matched_on', sa.String(), nullable=True),
    sa.Column('variants', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['terminology_concept.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['coding_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'code', name='uq_coding_candidate_item_code')
    )
    op.create_index(op.f('ix_coding_candidate_item_id'), 'coding_candidate', ['item_id'], unique=False)
    op.create_table('coding_decision',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['coding_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_coding_decision_item_active', 'coding_decision', ['item_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_coding_decision_item_id'), 'coding_decision', ['item_id'], unique=False)
    op.create_table('coding_candidate_score',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['coding_candidate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decision_id'], ['coding_decision.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_candidate_score_decision_id'), 'coding_candidate_score', ['decision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coding_candidate_score_decision_id'), table_name='coding_candidate_score')
    op.drop_table('coding_candidate_score')
    op.drop_index(op.f('ix_coding_decision_item_id'), table_name='coding_decision')
    op.drop_index('ix_coding_decision_item_active', table_name='coding_decision')
    op.drop_table('coding_decision')
    op.drop_index(op.f('ix_coding_candidate_item_id'), table_name='coding_candidate')
    op.drop_table('coding_candidate')
    op.drop_index(op.f('ix_coding_audit_event_item_id'), table_name='coding_audit_event')
    op.drop_index(op.f('ix_coding_audit_event_encounter_pk'), table_name='coding_audit_event')
    op.drop_table('coding_audit_event')
    op.drop_index(op.f('ix_coding_item_status'), table_name='coding_item')
    op.drop_index(op.f('ix_coding_item_encounter_pk'), table_name='coding_item')
    op.drop_table('coding_item')
    op.drop_index(op.f('ix_coding_encounter_status'), table_name='coding_encounter')
    op.drop_index(op.f('ix_coding_encounter_review_queue'), table_name='coding_encounter')
    op.drop_index(op.f('ix_coding_encounter_patient_id'), table_name='coding_encounter')
    op.drop_index(op.f('ix_coding_encounter_encounter_id'), table_name='coding_encounter')
    op.drop_table('coding_encounter')
    # ### end Alembic commands ###
